export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const PICTURES_FETCH_START = 'PICTURES_FETCH_START'
export const PICTURES_FETCH_SUCCESS = 'PICTURES_FETCH_SUCCESS'
export const PICTURES_SORT_UPDATE = 'PICTURES_SORT_UPDATE'
export const PICTURE_FETCH_SUCCESS = 'PICTURE_FETCH_SUCCESS'
export const PICTURE_FETCH_ERROR = 'PICTURE_FETCH_ERROR'
export const PICTURES_FILTER_UPDATE = 'PICTURES_FILTER_UPDATE'


